CREATE DATABASE SIEUTHI
ON PRIMARY 
	( NAME = SIEUTHI_data, 
	FILENAME = 'C:\COSODULIEU\SIEUTHI\SIEUTHI_data.mdf',
	SIZE = 25MB, 
	MAXSIZE = 40MB,
	FILEGROWTH = 1MB)
LOG ON
	( NAME = SIEUTHI_log,
	 FILENAME = 'C:\COSODULIEU\SIEUTHI\SIEUTHI_log.ldf', 
	 SIZE = 6MB, 
	 MAXSIZE = 8MB,
	 FILEGROWTH = 1MB)
USE SIEUTHI
GO
CREATE TABLE NHOMSANPHAM (
	[MaNhom] [int] PRIMARY KEY,
	[TenNhom] [nvarchar](15) NULL )
GO
CREATE TABLE NHACUNGCAP (
	 [MaNCC] [int] PRIMARY KEY,
	 [TenNcc] [nvarchar](40) NOT NULL,
	 [Diachi] [nvarchar](60) NULL,
	 [Phone] [nvarchar](24) NULL,
	 [SoFax] [nvarchar](24) NULL,
	 [DCMail] [nvarchar](50) NULL )
GO
CREATE TABLE SANPHAM (
	 [MaSp] [int] PRIMARY KEY,
	 [TenSp] [nvarchar](40) NOT NULL,
	 [MaNCC] [int] NULL,
	 [MoTa] [nvarchar](50) NULL,
	 [MaNhom] [int] NULL,
	 [Ðonvitinh] [nvarchar](20) NULL,
	 [GiaGoc] [money] NULL,
	 [SLTON] [int] NULL,
	 FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC),
     FOREIGN KEY (MaNhom) REFERENCES NHOMSANPHAM(MaNhom))
GO
CREATE TABLE NHANVIEN (
	 [MaNV] [nchar](5) PRIMARY KEY,
	 [TenNV] [nvarchar](40) NOT NULL,
	 [DiaChi] [nvarchar](60) NULL,
	 [Dienthoai] [nvarchar](24) NULL )
GO
CREATE TABLE KHACHHANG (
	 [MaKh] [nchar](5) NOT NULL,
	 [TenKh] [nvarchar](40) NOT NULL,
	 [LoaiKh] [nvarchar](3) NULL,
	 [DiaChi] [nvarchar](60) NULL,
	 [Phone] [nvarchar](24) NULL )
GO
CREATE TABLE HOADON (
	 [MaHD] [int] NOT NULL,
	 [NgayLapHD] [datetime] NULL,
	 [NgayGiao] [datetime] NULL,
	 [Noichuyen] [nvarchar](60) NOT NULL,
	 [MaNV] [nchar](5) NULL,
	 [MaKh] [nchar](5) NULL )
GO
CREATE TABLE CT_HOADON (
	 [MaHD] [int] NOT NULL,
	 [MaSp] [int] NOT NULL,
	 [Soluong] [smallint] NULL,
	 [Dongia] [money] NULL,
	 [ChietKhau] [money] NULL )
ALTER TABLE KHACHHANG ADD [SoFax] [nvarchar](24) Null
ALTER TABLE KHACHHANG ADD [DCMail] [nvarchar](50) Null
ALTER TABLE KHACHHANG ADD [DiemTL] [int]
ALTER TABLE KHACHHANG
ADD CONSTRAINT PK_KHACHHANG PRIMARY KEY (MaKH)
ALTER TABLE HOADON
ADD CONSTRAINT PK_HOADON PRIMARY KEY (MaHD)
ALTER TABLE CT_HOADON
ADD CONSTRAINT PK_CT_HOADON PRIMARY KEY (MaHD, MaSP)

ALTER TABLE HOADON WITH CHECK ADD FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
ALTER TABLE HOADON WITH CHECK ADD FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
ALTER TABLE CT_HOADON WITH CHECK ADD FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)
ALTER TABLE CT_HOADON WITH CHECK ADD FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)

ALTER TABLE HOADON ADD CONSTRAINT [HD_df] DEFAULT (getdate()) FOR
[NgayLapHD]

ALTER TABLE KHACHHANG WITH CHECK ADD CONSTRAINT [KH_ck] CHECK 
(([LoaiKH]='VL' OR [LoaiKH]='TV' OR [LoaiKH]='VIP'))
ALTER TABLE KHACHHANG CHECK CONSTRAINT [KH_ck]

ALTER TABLE SANPHAM WITH CHECK ADD CONSTRAINT [SP_ck] CHECK 
(([giagoc]>(0)))
ALTER TABLE SANPHAM CHECK CONSTRAINT [SP_ck]

ALTER TABLE SANPHAM WITH CHECK ADD CONSTRAINT [SP_ck1] CHECK 
(([slton]>(0)))
ALTER TABLE SANPHAM CHECK CONSTRAINT [SP_ck1]

ALTER TABLE SANPHAM WITH CHECK ADD CONSTRAINT [SanPham_ck] CHECK (([SlTon]>(0)))
ALTER TABLE SANPHAM CHECK CONSTRAINT [SanPham_ck]

ALTER TABLE HOADON WITH CHECK ADD CONSTRAINT [HD_ck] CHECK 
(([NgayLapHD]>=getdate()))
ALTER TABLE HOADON CHECK CONSTRAINT [HD_ck]

ALTER TABLE CT_HOADON WITH CHECK ADD CHECK (([chietkhau]>=(0)))
ALTER TABLE CT_HOADON WITH CHECK ADD CHECK (([soluong]>(0)))

ALTER TABLE HOADON ADD LoaiHD CHAR(1) DEFAULT 'N'
ALTER TABLE HOADON WITH CHECK ADD CONSTRAINT [LoaiHD_ck] CHECK ([LoaiHD] IN ('N', 'X', 'C', 'T'))
ALTER TABLE HOADON ADD CONSTRAINT [NgayGiao_ck] CHECK ([NgayGiao] >= [NgayLapHD])


